const softwareDeveloperData = {
  name: "RAHUL GUPTA",
  jobTitle: "Senior Backend Engineer",
  about: `Senior Backend Engineer with 5+ years across backend systems, DevOps, and financial-market automation. Currently at QuantDirection building high-availability auto-trading pipelines, APIs, CI/CD, and backend infrastructure. Strong in Node.js, Python, REST APIs, Docker, AWS, GCP, PostgreSQL, MongoDB, monitoring, and secure auth.`,
  email: "rahulgupta89343@gmail.com",
  contact: "7021091055",
  location: "Mumbai, India",
  links: [
    { name: "GitHub", url: "https://github.com/rahul1115" },
    { name: "LinkedIn", url: "https://www.linkedin.com/in/rahul1115/" },
    { name: "Website", url: "https://amrahul.in/" },
  ],
  skills: [
    "Node.js",
    "Python",
    "REST APIs",
    "AWS",
    "GCP",
    "Docker",
    "CI/CD",
    "DevOps",
    "PostgreSQL",
    "MongoDB",
    "Auth0",
    "API Development",
    "Webhooks",
    "System Monitoring",
    "Go",
    "PHP",
    "React.js",
    "Next.js",
    "Vue",
    "Shell Script",
    "Machine Learning",
    "Artificial intelligence",
    "Tensorflow",
  ],
  experiences: [
    {
      companyName: "QuantDirection (via Cloudstaff LLP)",
      duration: "Jan 2025 - Present",
      title: "Senior Software Engineer",
      location: "California, United States · Remote",
      description: [
        "Built and maintained backend infrastructure for <strong>high-availability auto-trading systems</strong> with strong focus on reliability and production stability.",
        "Designed and implemented <strong>auto-trading pipelines</strong> using <strong>webhooks</strong>, APIs, and third-party integrations after infrastructure was stabilized.",
        "Built <strong>CI/CD pipelines</strong> from scratch, enabling reliable and rapid deployments where none previously existed.",
        "Set up <strong>centralized logging</strong> and monitoring for full visibility into production trading operations.",
        "Resolved existing bugs and refactored <strong>legacy backend code</strong>, improving maintainability and laying the foundation for scalable development.",
        "Upgraded core projects and dependencies, reducing technical debt and improving system performance and security.",
        "Technologies: Node.js, Python, Docker, CI/CD, Webhooks, Cloud Infrastructure, System Monitoring.",
      ],
    },
    {
      companyName: "Nexsales Solutions Pvt Ltd",
      duration: "Oct 2022 - Jan 2025",
      title: "Software Engineer → Senior Software Engineer",
      location: "Mumbai, India",
      description: [
        "Built and maintained scalable backend services and <strong>REST APIs</strong> for lead-generation products used by thousands of users.",
        "Implemented <strong>single OAuth</strong> via Auth0 across all products, eliminating repeated logins and reducing sign-up drop-offs by <strong>20%</strong> while cutting security issues by <strong>30%</strong>.",
        "Managed <strong>CI/CD</strong> pipelines on <strong>GCP</strong> and used <strong>AWS</strong> for scalable cloud solutions.",
        "Revitalized a <strong>JavaScript</strong> scraping tool increasing speed by <strong>40%</strong>; automated keyword scraping via shell scripts.",
        "Collaborated with architects on scalable platform design, production debugging, and system stability.",
        "Technologies: Node.js, Python, Docker, Next.js, React.js, Vue.js, PostgreSQL, GCP, AWS, Auth0, DevOps.",
      ],
    },
    {
      companyName: "Saryu Business Solutions",
      duration: "Jan 2021 - Oct 2022",
      title: "Full Stack Web Developer",
      location: "Mumbai, India",
      description: [
        "Led the development of <strong>6+ full-stack web applications</strong> using <strong>PHP</strong> and <strong>MySQL</strong>, collaborating closely with designers and clients to boost user engagement by up to <strong>25%</strong>.",
        "Built a <strong>static site generator</strong> with custom templates to productize static website delivery, cutting development cost and time by <strong>40%</strong> across projects.",
        "Technologies: Node.js, Python, PHP, MySQL.",
      ],
    },
  ],
  courses: [
    {
      name: "Data Science Training",
      institution: "Udemy",
      start: "Jun 2022",
      end: "July 2022",
    },
    // {
    //   name: "Full Stack Software Development",
    //   institution: "NIIT",
    //   start: "Jun 2018",
    //   end: "Jan 2022",
    // },
  ],
  education: [
    {
      name: "M.Sc. Computer Science",
      institution: "K.C College",
      start: "2020",
      end: "2022",
    },
    {
      name: "B.Sc. Information Technology",
      institution: "Hinduja College",
      start: "2017",
      end: "2020",
    },
  ],
  interest: ["Chess", "Trekking", "Traveling"],
};

export default softwareDeveloperData;
