const softwareDeveloperData = {
  name: "RAHUL GUPTA",
  jobTitle: "Full stack Developer",
  about: `Full Stack Developer from Mumbai, passionate about web apps with Python, Node.js, React, and cloud. Always learning, especially in ML, neuroevolution, and GANs.`,
  links: [
    { name: "github", url: "https://github.com/rahul1115" },
    { name: "linkedin", url: "https://www.linkedin.com/in/rahul1115/" },
    { name: "webiste", url: "https://amrahul.in/" },
  ],
  skills: [
    "Docker",
    "GCP",
    "AWS",
    "Digital Ocean",
    "Node",
    "Python",
    "React",
    "Vue",
    "Bash",
    "Sql",
    "Mongo DB",
    "Power BI",
    "Tailwind CSS",
    "Pandas",
    "Numpy",
    "Matplotlib",
    "Git",
    "Github",
    "Linux",
    "Machin Learning",
    "Data Analytics",
  ],
  experiences: [
    {
      companyName: "Nexsales Solution Pvt Ltd",
      duration: "Apr 2024 - Present",
      title: "Senior Software Engineer 1",
      location: "Mumbai, India",
      description: [
        "Actively contribute to the development and maintenance of robust software systems for lead generation platform.",
        "Stay up-to-date with emerging technologies to drive innovation and optimize performance.",
        "Skilled in implementing OAuth systems for secure authentication.",
        "Docker, GCP, Auth0, OAuth2, Rect.js, Next.js, Node Js, Python, PostgreSQL, Power BI, Sveltekit.",
      ],
    },
    {
      companyName: "Nexsales Solution Pvt Ltd",
      duration: "Oct 2022 - Apr 2024",
      title: "Junior Software Developer",
      location: "Mumbai, India",
      description: [
        "Independently revamped an outdated javascript scraping tool, resulting in significantly improved efficiency",
        "Developed a shell script to automate keyword scraping from large files, streamlining the data collection process.",
        "Contributed to the development of over 6+ products, demonstrating versatility and adaptability.",
        "Node Js, Python, Docker, Rect.js, Next.js, Postgres.",
      ],
    },
    {
      companyName: "Saryu Business Solutions",
      duration: "Jan 2021 - Oct 2022",
      title: "Full-stack Web Developer",
      location: "Mumbai, India",
      description: [
        "Led development of full-stack PHP and MySQL projects, creating 6+ innovative websites.",
        "Built a static site generator from scratch, reducing project timelines by 40%.",
        "Node Js, PHP, MySQL, Node.js, Python.",
      ],
    },
  ],
  courses: [
    {
      name: "Power BI Desktop",
      institution: "Udemy",
      start: "Jun 2022",
      end: "July 2022",
    },
    {
      name: "Data Science Training",
      institution: "Udemy",
      start: "Jun 2022",
      end: "July 2022",
    },
    {
      name: "CareerReady Course",
      institution: "Antrang Foundation",
      start: "Jun 2021",
      end: "Aug 2021",
    },
    {
      name: "Full Stack software Development",
      institution: "NIIT",
      start: "Jun 2018",
      end: "Jan 2022",
    },
  ],
  education: [
    {
      name: "MSc Computer Science",
      institution: "K.C College",
      start: "2020",
      end: "2022",
    },
    {
      name: "Data Science Training",
      institution: "Hinduja College",
      start: "2017",
      end: "2020",
    },
  ],
  interest: ["Chess", "Trek", "Traveling"],
};

export default softwareDeveloperData;
