const softwareDeveloperData = {
  name: "RAHUL GUPTA",
  jobTitle: "Senior Software Engineer",
  about: `Senior Software Engineer with 5+ years across full-stack, DevOps, and quantitative trading systems. Currently at QuantDirection building high-availability auto-trading pipelines and backend infrastructure. Skilled in Node.js, Python, Go, Docker, GCP, AWS, and Next.js. Bridges the gap between quantitative logic and production-ready systems.`,
  email: "rahulgupta89343@gmail.com",
  contact: "7021091055",
  location: "Mumbai, India",
  links: [
    { name: "GitHub", url: "https://github.com/rahul1115" },
    { name: "LinkedIn", url: "https://www.linkedin.com/in/rahul1115/" },
    { name: "Website", url: "https://amrahul.in/" },
  ],
  skills: [
    "Node.js",
    "Python",
    "Go",
    "PHP",
    "Docker",
    "GCP",
    "AWS",
    "DevOps",
    "React.js",
    "Next.js",
    "Vue",
    "Shell Script",
    "PostgreSQL",
    "MongoDB",
    "Auth0",
    "Machine Learning",
    "Artificial intelligence",
    "Tensorflow",
    "API Development",
  ],
  experiences: [
    {
      companyName: "QuantDirection (via Cloudstaff LLP)",
      duration: "Jan 2025 - Present",
      title: "Senior Software Engineer",
      location: "California, United States · Remote",
      description: [
        "Sole engineer with both software and quant trading knowledge, driving development and automation of core systems powering trading strategies.",
        "Designed and implemented <strong>auto-trading pipelines</strong> using <strong>webhooks</strong> and third-party integrations for seamless execution.",
        "Built and maintained <strong>CI/CD workflows</strong> for reliable and rapid deployments across trading infrastructure.",
        "Set up <strong>centralized logging</strong> and system monitoring for improved visibility and issue tracking in production.",
        "Streamlined backend infrastructure to support <strong>high-availability</strong> trading operations.",
        "Technologies: Node.js, Python, CI/CD, Webhooks, Cloud Infrastructure, System Monitoring.",
      ],
    },
    {
      companyName: "Nexsales Solutions Pvt Ltd",
      duration: "Oct 2022 - Jan 2025",
      title: "Software Engineer → Senior Software Engineer",
      location: "Mumbai, India",
      description: [
        "Developed an <strong>Artificial Neural Network</strong> in <strong>TensorFlow</strong> with over <strong>95%</strong> accuracy; exported model from Python to JavaScript for improved performance.",
        "Implemented <strong>single OAuth</strong> via Auth0 across all products, eliminating repeated logins and reducing sign-up drop-offs by <strong>20%</strong> while cutting security issues by <strong>30%</strong>.",
        "Revitalized a <strong>JavaScript</strong> scraping tool increasing speed by <strong>40%</strong>; automated keyword scraping via shell scripts.",
        "Collaborated with architects to build scalable software for our lead generation platform, supporting thousands of users with high stability.",
        "Managed <strong>CI/CD</strong> pipelines on <strong>GCP</strong>, ensuring seamless deployments and leveraging <strong>AWS</strong> for scalable cloud solutions.",
        "Contributed to <strong>6+ products</strong>, adapting to various tech stacks across the platform.",
        "Technologies: Node.js, Python, Docker, Next.js, React.js, PostgreSQL, GCP, AWS, Auth0, DevOps.",
      ],
    },
    {
      companyName: "Saryu Business Solutions",
      duration: "Jan 2021 - Oct 2022",
      title: "Full Stack Web Developer",
      location: "Mumbai, India",
      description: [
        "Led the development of <strong>6+ full-stack web applications</strong> using <strong>PHP</strong> and <strong>MySQL</strong>, collaborating closely with designers and clients to boost user engagement by up to <strong>25%</strong>.",
        "Built a <strong>static site generator</strong> from scratch, reducing project timelines by <strong>40%</strong> and establishing a new standard for efficiency across future projects.",
        "Technologies: Node.js, Python, PHP, MySQL.",
      ],
    },
  ],
  courses: [
    {
      name: "Data Science Training",
      institution: "Udemy",
      start: "Jun 2022",
      end: "July 2022",
    },
    // {
    //   name: "Full Stack Software Development",
    //   institution: "NIIT",
    //   start: "Jun 2018",
    //   end: "Jan 2022",
    // },
  ],
  education: [
    {
      name: "M.Sc. Computer Science",
      institution: "K.C College",
      start: "2020",
      end: "2022",
    },
    {
      name: "B.Sc. Information Technology",
      institution: "Hinduja College",
      start: "2017",
      end: "2020",
    },
  ],
  interest: ["Chess", "Trekking", "Traveling"],
};

export default softwareDeveloperData;
